CREATE DATABASE rest_api;
\c rest_api;

CREATE TABLE userer(id SERIAL PRIMARY KEY,name VARCHAR,title VARCHAR,duty VARCHAR,dname VARCHAR);

CREATE TABLE news(id SERIAL PRIMARY KEY, header VARCHAR, content VARCHAR,author VARCHAR);

CREATE TABLE department(id SERIAL PRIMARY KEY,DName VARCHAR,DDescription VARCHAR,NEmployees VARCHAR);

CREATE TABLE user_in_department(id SERIAL PRIMARY KEY,usersId INTEGER,DepId INTEGER);


CREATE DATABASE rest_api_test WITH TEMPLATE rest_api;
